### ISSUE TITLE
[killOnWindows error] { [Error: spawn wmic ENOENT]

### ISSUE THREAD

**Issue by begend** [richard1122/vscode-youcompleteme#15]
my vscode output as follow, 3ks:

[getInstance] ycm is restarting
[start] data: 50293,����W����ץ)�,[object Object]
[processData: {"filepath_completion_use_working_dir":0,"auto_trigger":1,"min_num_of_chars_for_completion":2,"min_num_identifier_candidate_chars":0,"semantic_triggers":{},"filetype_specific_completion_to_disable":{"gitcommit":1},"seed_identifiers_with_syntax":0,"collect_identifiers_from_comments_and_strings":0,"collect_identifiers_from_tags_files":0,"max_num_identifier_candidates":10,"extra_conf_globlist":[],"global_ycm_extra_conf":"","confirm_extra_conf":true,"complete_in_comments":0,"complete_in_strings":1,"max_diagnostics_to_display":30,"filetype_whitelist":{"*":1},"filetype_blacklist":{"tagbar":1,"qf":1,"notes":1,"markdown":1,"unite":1,"text":1,"vimwiki":1,"pandoc":1,"infolog":1,"mail":1},"auto_start_csharp_server":1,"auto_stop_csharp_server":1,"use_ultisnips_completer":1,"csharp_server_port":0,"hmac_secret":"/8gZ9pBXBOqG+LLXpSkDyA==","server_keep_logfiles":0,"gocode_binary_path":"","rustSrcPath":""}]
[start] optionsFile: /var/folders/9n/yh5151xx7g34sm_k1ckzk07m0000gn/T/VSCodeYcmOptions-1477299539099
[_start] [ '/Users/baidu/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd',
  '--port=50293',
  '--options_file=/var/folders/9n/yh5151xx7g34sm_k1ckzk07m0000gn/T/VSCodeYcmOptions-1477299539099',
  '--idle_suicide_seconds=600' ]
[_start] process spawn success 8372
[start] ycm started: 8372
[killOnWindows error] { [Error: spawn wmic ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn wmic',
  path: 'wmic',
  spawnargs: 
   [ 'process',
     'where',
     '(ParentProcessId=8372)',
     'get',
     'processid' ] }
[saveYcmdPidWindows] windows ycmd pid=undefined
[ycm stderr] 2016-10-24 17:08:59,559 - INFO - Server shutting down

[ycm stdout] serving on http://127.0.0.1:50293

[_start exit] 0

**Comment by begend** [comment]
it seems that the option_file is non-existent。bug the ycmd server is alive.

**Comment by richard1122** [comment]
Looks like you're not using windows?

**Comment by richard1122** [comment]
I've updated a new version (1.0.24), could you please update to the newest version and try again?
