### ISSUE TITLE
why can not work on Ubuntu 16.04?

### ISSUE THREAD

**Issue by baoqingwutong** [richard1122/vscode-youcompleteme#17]
I'm new user, want use it in vs code, but it not work.
I install python3.5.2, and build ycmd successfully, then set ycmd.path. I alos install C/C++ extension(microsoft).
like this, string.push_back() not found!
![2016-10-27 17-31-33](https://cloud.githubusercontent.com/assets/23095898/19762166/7011e71a-9c6b-11e6-9714-2de7c7cd9b17.png)

**Comment by agauniyal** [comment]
Try turning off Microsoft C/C++ extension's autocomplete and then try..

**Comment by richard1122** [comment]
If you turned off MS C/C++ extension and still now working. Please set `ycmd.debug` true in your configuration file to see if there are any log useful.
