### ISSUE TITLE
Completions do not show up until manual invocation

### ISSUE THREAD

**Issue by agauniyal** [richard1122/vscode-youcompleteme#2]
I've to press `ctrl + space` everytime while writing code, nothing like the gifs on readme works here.

**[DEMO](http://webm.land/media/RkWn.webm)**

**Comment by richard1122** [comment]
Currently only dot(.) is the trigger character of completion. I will make it configurable.

**Comment by agauniyal** [comment]
@richard1122 `.` & `::` & `->` should be the defaults, don't you think?

**Comment by richard1122** [comment]
I agree.  :smile: 

In fact more than one characters (like `::`) might cause completion not working. I'm still investigate why.

**Comment by richard1122** [comment]
I've published a new version. 
Please have a try.

**Comment by agauniyal** [comment]
@richard1122 yup works perfectly now :tada: . Would you be adding more features like FixIts and others provided by Ycm?

**Comment by richard1122** [comment]
@agauniyal I changed it to ['.', ':', '<', '"', '=', '/'] like https://github.com/Microsoft/vscode/blob/master/src/vs/languages/handlebars/common/handlebars.ts#L168.

**Comment by richard1122** [comment]
@agauniyal I will add fix it, Goto(declaration, definition etc) soon.

**Comment by agauniyal** [comment]
Thankyou :smiley:

**Comment by richard1122** [comment]
@agauniyal Hi, I've added QuickFix to the newest version. Could you please have a try? ..

**Comment by agauniyal** [comment]
Yep, it works great 👍 👍  Thankyou for adding this 😄
