### ISSUE TITLE
can this choose different target for different platform？

### ISSUE THREAD

**Issue by lygstate** [richard1122/vscode-youcompleteme#21]

**Comment by richard1122** [comment]
Sorry I don't know what you exactly meaning?

This is a plugin for visual studio code. you can install this plugin on any platform with vscode. 

But I've not tested on OSX yet.

**Comment by agauniyal** [comment]
He probably meant cross-compilation target, which isn't handled by this plugin but the Microsoft C/C++ plugin.

**Comment by lygstate** [comment]
yes that's what I mean

**Comment by agauniyal** [comment]
@lygstate this plugin only provides autocompletion which will work for the machine you're developing at. For example, it won't complete `<unistd.h>` functions on windows because it simply isn't present.

**Comment by richard1122** [comment]
I think there 's nothing we can do here due to this is not what ycmd provides.
