### ISSUE TITLE
Support launching ycmd inside a VM.

### ISSUE THREAD

**Issue by nicber** [richard1122/vscode-youcompleteme#23]
I'd like to be able to configure ycmd to be launched inside a VM automatically.
It would be very useful for developing inside a VM, such as those created by Vagrant.

It can be done, now, but it requires installing a copy of all dependencies in the host and it may not be
possible if the host and VM run OSs different enough (such as Windows and a Linux distro).

**Comment by richard1122** [comment]
It's should be an feature of YCMD project rather than this plugin's.

It could be great if Ycmd provides an docker image or VM image.
