### ISSUE TITLE
`Invalid ycm path` error right after install & reload

### ISSUE THREAD

**Issue by Deilan** [richard1122/vscode-youcompleteme#28]
Got `[Ycm] Invalid ycm path` error right after the installation & reloading.

VS Code v.1.10.1.
Windows 8.1 x64.

![untitled](https://cloud.githubusercontent.com/assets/4777512/23610507/d4f42908-0283-11e7-94f3-b67cbf802a0f.png)

**Comment by richard1122** [comment]
please see [usage](https://github.com/richard1122/vscode-youcompleteme#usage) to config plugin and install ycmd.
