### ISSUE TITLE
WSL version of YCM?

### ISSUE THREAD

**Issue by DuIslingr** [richard1122/vscode-youcompleteme#29]
Not really an issue but more of a question. Is it possible to setup ycm on WSL and call that version with this plugin?

**Comment by richard1122** [comment]
I'm not sure.
I think install ycmd into WSL is possible.
But it will use toolchains on linux, which means you cannot call any windows API and any other limitation may appear.

**Comment by richard1122** [comment]
Please try https://code.visualstudio.com/docs/remote/remote-overview
