### ISSUE TITLE
lint on the fly.

### ISSUE THREAD

**Issue by xdidi3r** [richard1122/vscode-youcompleteme#30]
I do not know if on-the-fly checks can be made.
Your extension reduces my lot of work. Hope you can make it better!

**Comment by richard1122** [comment]
Some problems may happen if the extension calls ycmd with lint request too many times. Like no completion result produced and so on.

I'm not sure whether there are any limitations of ycmd or just the bug in my plugin.

I'll continue to investigate this problem and try to add an option like this PR    https://github.com/richard1122/vscode-youcompleteme/pull/18

**Comment by richard1122** [comment]
Finally I added lint on save option.
