### ISSUE TITLE
PAth error message.

### ISSUE THREAD

**Issue by pquodling** [richard1122/vscode-youcompleteme#31]
I have installed ycm but suspect something isn't right - I get an Error [Ycm] Invalid ycm path - I have googled this but not seen any other reports of this - I suspect something amiss in my setup - what should I be looking for.???

**Comment by richard1122** [comment]
please read configuration in readme https://github.com/richard1122/vscode-youcompleteme/blob/master/README.md

**Comment by ngmgit** [comment]
@pquodling  Iam using it on arch and installing `ncurses5-compat-lib` solved this issue for me.
But auto completion doesnt work properly yet. will make a separate issue for that.
