### ISSUE TITLE
Connect ycm plugin to ycmd running on remote server

### ISSUE THREAD

**Issue by morapet** [richard1122/vscode-youcompleteme#34]
Would it be possible to configure and use VSCode client to use/connect/run ycmd on remote server. (I have scenario where compilation tools are only available on remote build machines and editor should run on different machine)?

**Comment by richard1122** [comment]
How do you edit remote file with local editor like VSCode ?

Are you using NFS or Windows file sharing ?

**Comment by trevordixon** [comment]
When I've needed this, I've either mounted the remote filesystem using sshfs, or I've had another copy of the code checked out locally. In either case, I just need to be able to configure the plugin to map local paths to remote ones and connect to ycmd on some particular address. A string->string map could be used to configure path mapping: `{'/local/path/to/src': '/remote/path/to/src'}`.

**Comment by morapet** [comment]
@richard1122 I have it same as @trevordixon mentioned, I use sshfs or another copy (git cloned repo locally - this is preferred). Source code exists on both sides, but only the remote side have libraries and binaries to do the compilation, also the mapping file for paths could be useful (but I can have it mounted locally I a same way as on the remote machine).

**Comment by richard1122** [comment]
https://code.visualstudio.com/docs/remote/remote-overview

MS implemented this.
