### ISSUE TITLE
No completition for typdefs ?

### ISSUE THREAD

**Issue by Glog78** [richard1122/vscode-youcompleteme#36]
Here is a small example ->

https://pastebin.com/17Kuwg71

hello:: doesn't bring up a completition even the the typedef is defined.
hello. does work even i need to do a compile (a save wasn't enough)

**Comment by richard1122** [comment]
Hi, I'm not very familiar with c++ shared_ptr class.
When I'm trying your code, there are some errors.
It says shared_ptr is not defined, and I 've added "#include <memory>" 
And you should add an ; after class ups definition.

For the `hello::` completion.
I guess hello is an class instance, how could it produce any completion for `::` operator?
When I'm using `.`, it works fine:
![2017-05-26 14-01-40](https://cloud.githubusercontent.com/assets/2534277/26482782/eccdd9ba-41ae-11e7-8ae3-594f0839bbad.png)

And after I define an ptr instance inside ups class, It will produce completion results.

 
![2017-05-26 14-02-15](https://cloud.githubusercontent.com/assets/2534277/26482808/0b448600-41af-11e7-9f57-16e203775628.png)
