### ISSUE TITLE
Any reason using getType instead of getDoc for onHover?

### ISSUE THREAD

**Issue by atlas1017** [richard1122/vscode-youcompleteme#39]
It seems to me that the getDoc gives more detailed info about identifiers and getType sometimes returns useless msgs like "bound member function type".
Thanks!

**Comment by richard1122** [comment]
Hi, I've tried GetDoc subcommand before and it always provides nothing. (both on Windows and Fedora)
Have you tried to call GetDoc and get some correct results?

Thanks!

**Comment by joelhock** [comment]
check out pull request 45, which uses getDoc when available (which is only when there is doxygen documentation for the function), then the signature info that accompanies the completion for the function (which is more useful than getType for member functions, but can't figure out which overload is being used), and then falls back to getType for other things.
https://github.com/richard1122/vscode-youcompleteme/pull/45
