### ISSUE TITLE
turn off output panel unless required

### ISSUE THREAD

**Issue by agauniyal** [richard1122/vscode-youcompleteme#4]
The output panel of `ycm-language-server` keeps popping even when we're writing some stuff and takes up quite an amount of window space. And it does contains information but which is only relevant for debugging the extension itself, so it should be off by default and only open if we want it.

**Comment by richard1122** [comment]
I guess I've turned off every debug output when production build.
I'll check it again.

**Comment by agauniyal** [comment]
It occurs usually when I'm hovering and it cannot find it's type or including header files.
