### ISSUE TITLE
Better Installation description

### ISSUE THREAD

**Issue by ghost** [richard1122/vscode-youcompleteme#5]
I tried to get it to work but I couldn't make it. Also the instructions at ycmd did not help at all because I don't use vim and for windows there are so many vim references.

**Comment by richard1122** [comment]
I also developed and tested this extension on windows 10. It works the same as Linux.
For windows installation instruction, you may see this: https://github.com/Valloric/YouCompleteMe/blob/master/README.md#windows

The vim related part can easily be skipped.

Which means you clone ycmd, update submodules. Then follow the instructions to install dependencies and run `python install.py` with parameters you needed.

Also you may follow the vim instructions. The only difference is you can use Vundle to manage(clone) ycmd.

**Comment by ghost** [comment]
I tried that but I always got the error message that the path is not correct

**Comment by richard1122** [comment]
What's the exact error message? 
Did you set your ycmd and python correct?

**Comment by ghost** [comment]
[Ycm] Invalid ycm global extra config path
I only installed the tern-completer
my path is
"C:\Users\USERNAMER\vimfiles\bundle\YouCompleteMe\third_party\ycmd"

**Comment by richard1122** [comment]
That means you forget to specify the global extra config path. It's `ycmd.global_extra_config`
You can see: https://github.com/Valloric/YouCompleteMe/blob/master/README.md#the-gycm_global_ycm_extra_conf-option

**Comment by ghost** [comment]
Where should it point at?
Is there any indicator that it works?

**Comment by richard1122** [comment]
I think it might not be an error. I'll fix it today. Due to you may not provide global conf file, just use your local's.

**Comment by ghost** [comment]
I don't have a conf file at all I think.

**Comment by richard1122** [comment]
The conf file (.ycm_extra_conf.py) is needed by ycmd backend. 
You can see explanation here: https://github.com/Valloric/YouCompleteMe/blob/master/README.md#c-family-semantic-completion

**Comment by ghost** [comment]
I better stick to intellisense. This is way to complicated.
