### ISSUE TITLE
can't complete when using global namespace declaration. 

### ISSUE THREAD

**Issue by Yiklek** [richard1122/vscode-youcompleteme#52]
When I use global namespace,it can't list suggestions.  
But YouCompleteMe works when I use gvim. 
Both .ycm_extra_conf.py are same.
My system is Windows 10.

#### vscode
![image](https://user-images.githubusercontent.com/21033316/39626115-3f41360a-4fd3-11e8-8bd5-ee0c7d329d38.png)

#### gvim
![image](https://user-images.githubusercontent.com/21033316/39626190-81232ce0-4fd3-11e8-8864-7d9e60423aa6.png)

**Comment by richard1122** [comment]
Try using `ctrl + space` to trigger completion.
