### ISSUE TITLE
Does it implement a Language Server Protocol server wrapping ycmd?

### ISSUE THREAD

**Issue by romix** [richard1122/vscode-youcompleteme#6]
This project looks awesome! 

My understanding of how it works:
- It implements a Language Server Protocol as defined by Microsoft, RedHat & others.
- The server is just a wrapper, which delegates all real processing to YCMD.

It is a correct understanding?

Does it mean that it can be used with any Language Server Protocol client, e.g. Atom-based editors, Eclipse, etc?

**Comment by romix** [comment]
If my understanding is correct, it kind of implements https://github.com/Valloric/ycmd/issues/593, which I asked for, though it does it in a somewhat different way, without changing the YCMD. I suggested to extends YCMD with a native LSP support.

**Comment by romix** [comment]
Or may be I misunderstood and it runs inside VSCode only? I.e. it is not really a server accepting JSON requests over HTTP? If this is the case, would it be difficult to make a stand-alone Language Server Protocol server out of it?

**Comment by richard1122** [comment]
> It implements a Language Server Protocol as defined by Microsoft, RedHat & others.

Yes.

> The server is just a wrapper, which delegates all real processing to YCMD.

You can see code at https://github.com/richard1122/vscode-youcompleteme/blob/master/server/src/server.ts#L13 
The server part dependents on `vscode-languageserver`

I'm not sure what's the correct way to implement https://github.com/Microsoft/language-server-protocol on platform independent way. 
Do you have any idea?

**Comment by romix** [comment]
I looked at the source code link you provided. It has a comment "The connection uses Node's IPC as a transport".  So currently, it is only started from inside VSCode and cannot be used from outside, right? 

If it would be possible to also use Node's HTTP transport and run the server on a standalone Node.JS server, outside of VSCode, then it could be used by other editors without a need to start VSCode I guess.

> I'm not sure what's the correct way to implement https://github.com/Microsoft/language-server-protocol on platform independent way. 

I'm not sure what you mean by a platform-independent way. The protocol itself just explains what kind of payload (i.e. JSON content) you send to the server and what you get back. Clients communicate with the server over a network. They don't care which language is used internally to implement the server itself. It can be a JavaScript implementation running e.g. on top of a Node.JS, or it can be implemented in Java or Ruby or Python. As long as it can receive and process requests according to the language-server-protocol specification it is fine.

**Comment by romix** [comment]
This link seems to be related: https://github.com/Microsoft/vscode-languageserver-node

Seems like the server can run on Node.JS outside of VScode....

**Comment by richard1122** [comment]
I've read some code of vscode-languageserver-node server part, along with vscode-languageserver-protocol, it looks not difficult to implement an server.

Would you please talk with ycmd's developers to see if we can add language server protocol directly into ycmd server. And I'm glad to help.

I think this would be better rather than implement a separate server and then call ycmd.

**Comment by romix** [comment]
Good to hear from you, @richard1122!

I totally agree with you. I've tried to convince ycmd's developers that adding the language server protocol directly to ycmd server would be much easier. Please see the discussion here: https://github.com/Valloric/ycmd/issues/593 and here: https://github.com/Valloric/ycmd/issues/515. 

As you can see, it looks like they don't want to invest any effort into the implementation yet. But may be if someone else (e.g. you) implements it and submits a pull request they would accept it?

**Comment by richard1122** [comment]
Looks they have no interest implementing lsp-server in ycmd.
