### ISSUE TITLE
Custom [go to definition] Shortcuts

### ISSUE THREAD

**Issue by vernon2gh** [richard1122/vscode-youcompleteme#60]
hello:
I have vscode-youcompleteme and vscode-gnu-global Plug，two plug-in [go to definition] is the same, It looks a bit confusing, So I want to customize the shortcuts vscode-youcompleteme [go to definition], What should I do?

thanks

**Comment by richard1122** [comment]
I think goto is a language server api. Not a command shortcut.

**Comment by vernon2gh** [comment]
[go to definition] how to separate out into another name or command?

**Comment by richard1122** [comment]
Here's the code to find the definition, it only response with a location, and vscode will jump to.
https://github.com/richard1122/vscode-youcompleteme/blob/master/server/src/server.ts#L118

I'm not sure how to make extensions to jump to the file and location, but if you are willing to take some investigation, PR's are welcome.
