### ISSUE TITLE
Add a configuration possibility to use an already running version of YCMD

### ISSUE THREAD

**Issue by romix** [richard1122/vscode-youcompleteme#7]
It would be nice if one could optionally configure the tool to use an existing running version of YCMD. 

It could be useful, if you use different editors using YCMD simultaneously, e.g. VIM, VSCode, etc. This way they can all use the same instance if YCMD instead of starting their own and wasting CPU & memory.

**Comment by richard1122** [comment]
Correctly we could not do it. Each ycmd instance is configured an unique HMAC key when startup.
