### ISSUE TITLE
support completion of system header files

### ISSUE THREAD

**Issue by agauniyal** [richard1122/vscode-youcompleteme#9]
**FEATURE REQUEST** - 

Need the plugin to autocomplete system headers, like if I type `#include <` it should start providing suggestions for atleast the c++ standard headers.

**Comment by richard1122** [comment]
I agree it would be necessary. I'll test if ycmd could provide header completions.

**Comment by richard1122** [comment]
Ycmd already provided files. I missed it somehow.
